### ISSUE TITLE
Edição 2 - 03/06/2019

### ISSUE THREAD

**Issue by marcobrunodev** [CollabCodeTech/weekly#1]
### Edição 2 da CollabCode Weekly.

Ajude a comunidade divulgando os conteúdos que você gostou e te ajudou na vida. Esse conteúdo não precisa ser mega novo, o mais importante é ele ter te ajudado ou que você tenha escrito para ajudar a galera. 

**Para mandar sua sugestão não crie novas issue apenas 
responda esssa!**

Por favor, siga o template a seguir para facilitar a vida dos curadores:

```
**[Título](URL)**
Rápida descrição
*Categoria*
*Idioma*
```

Temos as categorias a seguir, mas se seu conteúdo não está em uma das categorias não tem problema, crie a sua categoria e manda ver, só não deixe de compartilhar o conteúdo conosco!

**Categorias**
- Artigos
- Vídeos
- Post
- Podcast
- Lives
- Eventos
- Meetup
- Outros 😉

Conteúdo passando pela curadoria será divulgado no [twitter da CollabCode](http://twitter.com/collabcodetech) e por email que sai toda segunda-feira.

Logo, logo. Indicações dos conteúdos retornaram Collabs, a moeda da comunidade 😄

**Comment by marcobrunodev** [comment]
[AWS Serverless - Explorando falhas comuns de segurança](https://medium.com/@oieduardorabelo/aws-serverless-explorando-falhas-comuns-de-seguran%C3%A7a-f14dfda1f35b)
Fala de uma pequena introdução de **Serveless**, depois mostra uma injeção de dados em eventos.

*Artigo*
*PT-BR*

**Comment by alexandreramosdev** [comment]
[Unform: the definitive form library for React apps ](https://dev.to/italomlp/unform-the-definitive-form-library-for-react-apps-35lh)
Fala sobre uma nova lib criada pelo pessoal da **Rocketseat** para lida com formularios de forma mais facil e perfomatica.
repor:  [unform](https://github.com/Rocketseat/unform)

Artigos
Inglês

**Comment by operfildoluiz** [comment]
**[podTag: Trabalho remoto](URL)**
Conversamos sobre os desafios de implementar e administrar uma cultura de trabalho remoto nas organizações
*Categoria*: Podcasts
*Idioma*: pt-BR

**Comment by ruanvalente** [comment]
**[MÁSCARAS PARA FORMULÁRIO EM VANILLA JAVASCRIPT](https://youtu.be/r-8isv_TnVA)**

Neste vídeo o Fernando Daciuk mostra como criar algumas máscaras 
simples para campos de formulário, como telefone, CPF, etc usando apenas Javascript.

_Categoria_: Vídeos
_Idioma_: PT-BR

**Comment by oieduardorabelo** [comment]
olá @MarcoBrunoBR, obrigado por linkar meu Medium. Normalmente indico meus conteúdos no BrazilJS Weekly pela consistência da equipe. Eu escrevo semanalmente um artigo no meu [Dev.to](http://dev.to/oieduardorabelo) ou [Medium](http://medium.com/@oieduardorabelo) pessoal. Algumas vezes são postagens cruzadas também. Pelo formato que você está seguindo aqui (baseado no BrazilJS Weekly) e para evitar a duplicação de links em ambos (por lá eu contribuo semanalmente desde Março de 2016, tenho um carinho grande e evito postar o mesmo link em outros boletins), fico a disposição para planejarmos conteúdo curado para o CollabCode Weekly. Também já contribuí para plataformas como [Schot.io](http://scotch.io), [Ponyfoo](https://ponyfoo.com), [Codeburst.io](https://codeburst.io) e [FreeCodeCamp](http://freecodecamp.org). Pode me mandar uma [mensagem no Twitter](https://mobile.twitter.com/@oieduardorabelo) :wave:

**Comment by marcobrunodev** [comment]
> olá @MarcoBrunoBR, obrigado por linkar meu Medium. Normalmente indico meus conteúdos no BrazilJS Weekly pela consistência da equipe. Eu escrevo semanalmente um artigo no meu [Dev.to](http://dev.to/oieduardorabelo) ou [Medium](http://medium.com/@oieduardorabelo) pessoal. Algumas vezes são postagens cruzadas também. Pelo formato que você está seguindo aqui (baseado no BrazilJS Weekly) e para evitar a duplicação de links em ambos (por lá eu contribuo semanalmente desde Março de 2016, tenho um carinho grande e evito postar o mesmo link em outros boletins), fico a disposição para planejarmos conteúdo curado para o CollabCode Weekly. Também já contribuí para plataformas como [Schot.io](http://scotch.io), [Ponyfoo](https://ponyfoo.com), [Codeburst.io](https://codeburst.io) e [FreeCodeCamp](http://freecodecamp.org). Pode me mandar uma [mensagem no Twitter](https://mobile.twitter.com/@oieduardorabelo) wave

Estamos precisando de pessoas no time da curadoria dos conteúdos que a galera indicam aqui. Você quer fazer parte desse time @oieduardorabelo?

Ah! Outro ponto, antes eu trabalhava em um empresa e ao mesmo tempo na CollabCode, agora estou :100:% na CollabCode e com isso estamos conseguindo fazer muito mais dos nossos objetivos, e no momento estamos passando todos nossos projetos para OpenSource e organizando o GitHub pra isso, então logo logo terá uns projetos legais, se quiser mandar um PRs ficarei muito feliz :-)

**Comment by CristianoRC** [comment]
**[Localhost na web de maneira fácil — Serveo](https://medium.com/cristiano-cunha/expor-localhst-web-54744cf5ffd2)**
Como expor seu "localhost" na web em poucos passos.
*Artigos*
*pt-br*

**Comment by TiagoCunhaF** [comment]
**[Behind the Code - Evento IBM](https://maratona.dev/ibm-cloud/)**

O que é a Maratona
A Maratona Behind The Code é uma competição virtual com 9 desafios de programação que vão testar seus conhecimentos técnicos! Quer programar, aprimorar seus skills nas mais novas tecnologias de mercado e ainda fazer parte de um ranking com os 100 melhores desenvolvedores do Brasil? Então você não pode deixar de participar!

21/05 A 06/07: GET READY
Aprimore seus skills: confira as tecnologias que serão essenciais para os desafios. [Lista das tecnologias](https://maratona.dev/ibm-cloud/)

06/07: LARGADA
Os desafios serão lançados semanalmente, neste portal, de 6 a 28 de julho – fique ligado

15/08: FAÇAM SUAS MALAS
Os TOP 100 selecionados ganharão um final de semana na Praia do Forte para disputar o último desafio presencialmente

**[Inscrição Gratuita: https://maratona.dev/registro?id=103233](https://maratona.dev/registro?id=103233)**

* Eventos
* pt-br

**Comment by marcobrunodev** [comment]
**[Tecnologias no Nubank: 3 anos depois – Hipsters #150](https://hipsters.tech/tecnologias-no-nubank-3-anos-depois-hipsters-150/)**

Parece que o Flutter está saindo da moda e virando tendência, acho que chegou a hora de estudar ele de vez! O NuBank está adotando fortemente em seus apps.

*PodTag*
*PT-BR*

**Comment by marcobrunodev** [comment]
**[Flutter: porque você deveria apostar nesta tecnologia](https://medium.com/tableless/flutter-porque-voc%C3%AA-deveria-apostar-nesta-tecnologia-94a510fffd18)**

O Fabio Santana explica alguns pontos bem relevantes do Flutter, e esses pontos tornará ele de uma moda para uma tendência do mercado.

*Artigo*
*PT-BR*

**Comment by marcobrunodev** [comment]
**[DevWars](https://github.com/DevWars/devwars-live)**

Repositório de um projeto onde dois time podem entrar em combate!!!

*Repositório*
*EN*

**Comment by f0ntana** [comment]
**[dbeaver](https://dbeaver.io)**
Ferramenta de banco de dados multiplataforma gratuita para desenvolvedores
*Database tool*
*EN*

**Comment by marcobrunodev** [comment]
**[Svelte](https://svelte.dev/)**

Framework que não usa Virtual DOM e tem uma estrutura similar a Vue e React

*Framework*
*EN*

**Comment by lucaspdroz** [comment]
**[jfa-pwa-toolkit](https://github.com/jfadev/jfa-pwa-toolkit?fbclid=IwAR1uNOjOtg8cl8xG1r7E9Lmuysa8St656PO0m-25Gg_4OY9s-j8sF2NxBvs)**
Uma forma simples de iniciar um projeto PWA
*Outros *
*EN*

**Comment by marcobrunodev** [comment]
**[FLUTTER EM 6 MINUTOS: Tudo Que Você Precisa Saber para Começar!](https://www.youtube.com/watch?v=jbAh5R8CH_o)**

Vídeo da DevMedia que acho divertido como todos e bem informativo, nesse é tirado dúvidas introdutorias do Flutter e porque eles acreditam que ele será algo muito adota pelo mercado de trabalho, 

*Vídeo*
*PT-BR*

**Comment by ruanvalente** [comment]
[[Front-End] Svelte - Criando um componente de Todo List](https://www.youtube.com/watch?v=EMy7e890wIQ)

Neste vídeo Matheus Castiglioni mostra um pouco sobre o **Svelte** e como dar os seus primeiros passos criando um componente de Todo List.

_Vídeo_
_PT-BR_

**Comment by marcobrunodev** [comment]
> [[Front-End] Svelte - Criando um componente de Todo List](https://www.youtube.com/watch?v=EMy7e890wIQ)
> 
> Neste vídeo Matheus Castiglioni mostra um pouco sobre o **Svelte** e como dar os seus primeiros passos criando um componente de Todo List.
> 
> _Vídeo_
> _PT-BR_

Ontem estava estudando um pouco do Svelte, vou ver esse vídeo agora :-)

**Comment by ruanvalente** [comment]
[Autenticação com Hello.js no Quasar Framework](https://imasters.com.br/front-end/autenticacao-com-hello-js-no-quasar-framework)

Neste artigo **Patrick Pinheiro Monteiro** traz uma introdução com o procedimento de autenticação usando redes sociais. Usando um plugin muito interessante, chamado [hello.js](https://adodson.com/hello.js/#install).

_Artigo_
_PT-BR_

**Comment by joviane** [comment]
[Coisas que eu não sei by Dan Abramov](https://overreacted.io/things-i-dont-know-as-of-2018/)

Artigo muito interessante do final do ano passado que o Dan Abramov (co-autor do Redux, trabalha no Facebook desenvolvendo o React) escreveu sobre as coisas que ele não sabe e que todo mundo acha que ele sabe. Ele foi duramente criticado pela comunidade de devs rockstars por não saber algumas das coisas mas é bacana para percebermos que até os devs que estão no topo tem seus gaps de conhecimento. Precisamos acreditar um pouco mais em nós mesmos e ter menos síndrome do Impostor.

_Post_
_EN_

**Comment by operfildoluiz** [comment]
**[Progressive Web App: uma alternativa aos aplicativos nativos](https://blog.impulso.network/progressive-web-apps/)**
Como funciona e como implementar uma Progressive Web App do zero :)

*Categoria*: Post
*Idioma*: pt-BR

**Comment by raulpesilva** [comment]
**[Complete React Tutorial (& Redux) #22 - Lifecycle Methods](https://www.youtube.com/watch?v=iYz2OKWO09U)**
Mostra o funcionamento dos métodos de construção, antes e depois dela, update e de desmontar os componentes, muito utilizado pra dar comportamento e ações na hora de construir a aplicação. e uma pequena parte sobre redux.
*Video*
*en*
