### ISSUE TITLE
Intro to React-Hooks

### ISSUE THREAD

**Issue by efeeseao** [CollabCodeTech/weekly#2]
https://css-tricks.com/intro-to-react-hooks/
Um conteúdo bacana que eu li no css-tricks, sobre o React-Hooks.

**Comment by marcobrunodev** [comment]
@codder404 não crie uma nova issue, responda na issue da semana, que é essa aqui: https://github.com/CollabCodeTech/weekly/issues/1

Ah! e por favor, siga a esttrura proposta no issue https://github.com/CollabCodeTech/weekly/issues/1
