### ISSUE TITLE
Intro Vuejs, Criar sites a partir do layout dos inscritos.

### ISSUE THREAD

**Issue by jacksonbss** [CollabCodeTech/weekly#4]
Fazer alguns vídeos e lives sobre vuejs, resolver alguns desafios front-end e desenvolver sites criados pelos inscritos

**Comment by marcobrunodev** [comment]
Por favor, responda a issue https://github.com/CollabCodeTech/weekly/issues/1

não crie novas issue

**Comment by marcobrunodev** [comment]
Gostei bastante das ideias, Principalmente a de fazer sites criados pelos inscritos :-)
